openapi: 3.1.0
info:
  title: Merchant API
  version: 1.0.0
  x-logo:
    url: https://uzumbank.uz/_nuxt/img/uzumbank-logo-light.f4c13a0.svg
    href: /
  description: >
    **Merchant API** –ø–æ–∑–≤–æ–ª—è–µ—Ç –ø–∞—Ä—Ç–Ω–µ—Ä–∞–º –ø—Ä–∏–Ω–∏–º–∞—Ç—å –ø–ª–∞—Ç–µ–∂–∏ —á–µ—Ä–µ–∑ –º–æ–±–∏–ª—å–Ω–æ–µ
    –ø—Ä–∏–ª–æ–∂–µ–Ω–∏–µ Uzum Bank. –ö–æ–≥–¥–∞ –∫–ª–∏–µ–Ω—Ç –æ–ø–ª–∞—á–∏–≤–∞–µ—Ç —É—Å–ª—É–≥—É, –º—ã –æ—Ç–ø—Ä–∞–≤–ª—è–µ–º –Ω–∞ –≤–∞—à
    —Å–µ—Ä–≤–µ—Ä [–≤–µ–±—Ö—É–∫–∏](#tag/Vebhuki) ‚Äî —ç—Ç–æ HTTP POST-–∑–∞–ø—Ä–æ—Å—ã —Å –¥–∞–Ω–Ω—ã–º–∏ –æ –ø–ª–∞—Ç–µ–∂–µ.


    –ß—Ç–æ–±—ã –∏–Ω—Ç–µ–≥—Ä–∏—Ä–æ–≤–∞—Ç—å—Å—è, —Ä–µ–∞–ª–∏–∑—É–π—Ç–µ –Ω–∞ —Å–≤–æ–µ–π —Å—Ç–æ—Ä–æ–Ω–µ –æ–±—Ä–∞–±–æ—Ç—á–∏–∫–∏ –≤–µ–±—Ö—É–∫–æ–≤ –∏
    —Ñ–æ—Ä–º–∏—Ä—É–π—Ç–µ –æ—Ç–≤–µ—Ç—ã –ø–æ —ç—Ç–æ–π —Å–ø–µ—Ü–∏—Ñ–∏–∫–∞—Ü–∏–∏.


    #### ‚öôÔ∏è –û—Å–Ω–æ–≤–Ω—ã–µ –≤–æ–∑–º–æ–∂–Ω–æ—Å—Ç–∏

    - –ü—Ä–æ–≤–µ—Ä–∫–∞ –≤–æ–∑–º–æ–∂–Ω–æ—Å—Ç–∏ –ø—Ä–æ–≤–µ–¥–µ–Ω–∏—è –ø–ª–∞—Ç–µ–∂–∞

    - –°–æ–∑–¥–∞–Ω–∏–µ (–∏–Ω–∏—Ü–∏–∞—Ü–∏—è) –ø–ª–∞—Ç–µ–∂–Ω–æ–π —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏

    - –ü–æ–¥—Ç–≤–µ—Ä–∂–¥–µ–Ω–∏–µ —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏

    - –û—Ç–º–µ–Ω–∞ —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏

    - –ü—Ä–æ–≤–µ—Ä–∫–∞ —Å—Ç–∞—Ç—É—Å–∞ —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏


    #### üöÄ **–ë—ã—Å—Ç—Ä—ã–π —Å—Ç–∞—Ä—Ç**

    - [–ü—Ä–æ—Ü–µ—Å—Å –ø—Ä–∏—ë–º–∞ –ø–ª–∞—Ç–µ–∂–∞](#section/Process-priyoma-platezha)

    - [–ê–≤—Ç–æ—Ä–∏–∑–∞—Ü–∏—è](#section/Avtorizaciya) 

    - [–§–æ—Ä–º–∞—Ç –∑–∞–ø—Ä–æ—Å–æ–≤](#section/Format-zaprosov)

    - [–í–µ–±—Ö—É–∫–∏](#tag/Vebhuki)


    ---


    # –ü—Ä–æ—Ü–µ—Å—Å –ø—Ä–∏—ë–º–∞ –ø–ª–∞—Ç–µ–∂–∞


    –ü—Ä–æ—Ü–µ—Å—Å –ø—Ä–∏—ë–º–∞ –ø–ª–∞—Ç–µ–∂–∞ —á–µ—Ä–µ–∑ –º–æ–±–∏–ª—å–Ω–æ–µ –ø—Ä–∏–ª–æ–∂–µ–Ω–∏–µ Uzum Bank —Å–æ—Å—Ç–æ–∏—Ç –∏–∑ —Ç—Ä—ë—Ö
    —ç—Ç–∞–ø–æ–≤:


    1. –ü—Ä–æ–≤–µ—Ä–∫–∞ –≤–æ–∑–º–æ–∂–Ω–æ—Å—Ç–∏ –ø—Ä–æ–≤–µ–¥–µ–Ω–∏—è –ø–ª–∞—Ç–µ–∂–∞

    2. –°–æ–∑–¥–∞–Ω–∏–µ —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏

    3. –ü–æ–¥—Ç–≤–µ—Ä–∂–¥–µ–Ω–∏–µ —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏


    ## –ü—Ä–æ–≤–µ—Ä–∫–∞ –≤–æ–∑–º–æ–∂–Ω–æ—Å—Ç–∏ –ø—Ä–æ–≤–µ–¥–µ–Ω–∏—è –ø–ª–∞—Ç–µ–∂–∞


    –ü–æ—Å–ª–µ –≤—ã–±–æ—Ä–∞ —É—Å–ª—É–≥–∏ –∏ —É–∫–∞–∑–∞–Ω–∏—è –Ω–µ–æ–±—Ö–æ–¥–∏–º—ã—Ö –¥–∞–Ω–Ω—ã—Ö, –Ω–∞–ø—Ä–∏–º–µ—Ä, –Ω–æ–º–µ—Ä–∞ –ª–∏—Ü–µ–≤–æ–≥–æ
    —Å—á—ë—Ç–∞, –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—å –ø–µ—Ä–µ—Ö–æ–¥–∏—Ç –∫ —ç—Ç–∞–ø—É –ø—Ä–æ–≤–µ—Ä–∫–∏ –≤–æ–∑–º–æ–∂–Ω–æ—Å—Ç–∏ –ø—Ä–æ–≤–µ–¥–µ–Ω–∏—è
    –ø–ª–∞—Ç–µ–∂–∞. –ù–∞ —ç—Ç–æ–º —ç—Ç–∞–ø–µ Uzum Bank –≤—ã–∑—ã–≤–∞–µ—Ç –≤–µ–±—Ö—É–∫ [check](#operation/check)
    –Ω–∞ —Å—Ç–æ—Ä–æ–Ω–µ –ø–∞—Ä—Ç–Ω—ë—Ä–∞ –¥–ª—è –ø–æ–¥—Ç–≤–µ—Ä–∂–¥–µ–Ω–∏—è –≤–æ–∑–º–æ–∂–Ω–æ—Å—Ç–∏ –ø—Ä–æ–≤–µ–¥–µ–Ω–∏—è –ø–ª–∞—Ç–µ–∂–∞. –î–∞–Ω–Ω—ã–µ
    –Ω–µ–æ–±—Ö–æ–¥–∏–º—ã–µ –¥–ª—è —Å–æ–≤–µ—Ä—à–µ–Ω–∏—è –ø–ª–∞—Ç–µ–∂–∞ –ø–µ—Ä–µ–¥–∞—é—Ç—Å—è –≤ –æ–±—ä–µ–∫—Ç–µ `params`.


    <a href='/img/merchant-api/ru-merchant-verify-transfer.png'
    target='_blank'><img style="display: block; margin: 0 auto; max-width:70%;
    height: auto;"
    src='/img/merchant-api/ru-merchant-verify-transfer.png'/></a>.


    ## –°–æ–∑–¥–∞–Ω–∏–µ —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏


    –ï—Å–ª–∏ –ø–æ —Ä–µ–∑—É–ª—å—Ç–∞—Ç–∞–º –ø—Ä–æ–≤–µ—Ä–∫–∏ –≤–æ–∑–º–æ–∂–Ω–æ—Å—Ç—å –ø—Ä–æ–≤–µ–¥–µ–Ω–∏—è –ø–ª–∞—Ç–µ–∂–∞ –ø–æ–¥—Ç–≤–µ—Ä–∂–¥–µ–Ω–∞,
    Uzum Bank –≤—ã–∑—ã–≤–∞–µ—Ç –≤–µ–±—Ö—É–∫ [create](#operation/create) –¥–ª—è —Å–æ–∑–¥–∞–Ω–∏—è
    —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏.


    <a href='/img/merchant-api/ru-merchant-create-transaction.png'
    target='_blank'><img style="display: block; margin: 0 auto; max-width:70%;
    height:auto;"
    src='/img/merchant-api/ru-merchant-create-transaction.png'/></a>.


    ## –ü–æ–¥—Ç–≤–µ—Ä–∂–¥–µ–Ω–∏–µ —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏


    –ü–æ—Å–ª–µ —É—Å–ø–µ—à–Ω–æ–≥–æ —Å–æ–∑–¥–∞–Ω–∏—è —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ Uzum Bank —Å–ø–∏—Å—ã–≤–∞–µ—Ç —Å—Ä–µ–¥—Å—Ç–≤–∞ —Å
    –ø–ª–∞—Ç—ë–∂–Ω–æ–≥–æ –∏–Ω—Å—Ç—Ä—É–º–µ–Ω—Ç–∞ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—è –∏ –∑–∞—á–∏—Å–ª—è–µ—Ç –∏—Ö –Ω–∞ –≤–∞—à —Ä–∞—Å—á—ë—Ç–Ω—ã–π —Å—á—ë—Ç.
    –ó–∞—Ç–µ–º Uzum Bank –≤—ã–∑—ã–≤–∞–µ—Ç –≤–µ–±—Ö—É–∫ [confirm](#operation/confirm) –¥–ª—è
    –ø–æ–¥—Ç–≤–µ—Ä–∂–¥–µ–Ω–∏—è —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏. –í–∞–º –Ω–µ–æ–±—Ö–æ–¥–∏–º–æ –æ–±—Ä–∞–±–æ—Ç–∞—Ç—å —ç—Ç–æ—Ç –∑–∞–ø—Ä–æ—Å,
    –ø—Ä–µ–¥–æ—Å—Ç–∞–≤–∏—Ç—å —É—Å–ª—É–≥—É –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é –∏ —Å—Ñ–æ—Ä–º–∏—Ä–æ–≤–∞—Ç—å –æ—Ç–≤–µ—Ç.


    <a href='/img/merchant-api/ru-merchant-confirm-transaction.png'
    target='_blank'><img style="display: block; margin: 0 auto; max-width:70%;
    height:auto;"
    src='/img/merchant-api/ru-merchant-confirm-transaction.png'/></a>.


    –ï—Å–ª–∏ –ø—Ä–∏ –æ–±—Ä–∞–±–æ—Ç–∫–µ –∑–∞–ø—Ä–æ—Å–∞ –≤–æ–∑–Ω–∏–∫–ª–∞ –æ—à–∏–±–∫–∞ —Å–µ—Ä–≤–µ—Ä–∞ –Ω–∞ —Å—Ç–æ—Ä–æ–Ω–µ –ø–∞—Ä—Ç–Ω—ë—Ä–∞ –∏–ª–∏
    –ø—Ä–æ–∏–∑–æ—à—ë–ª —Ç–∞–π–º-–∞—É—Ç, Uzum Bank –≤—ã–∑—ã–≤–∞–µ—Ç –≤–µ–±—Ö—É–∫ [status](#operation/status)
    –¥–ª—è –ø—Ä–æ–≤–µ—Ä–∫–∏ —Å—Ç–∞—Ç—É—Å–∞ —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏. –≠—Ç–æ—Ç –≤—ã–∑–æ–≤ –ø–æ–≤—Ç–æ—Ä—è–µ—Ç—Å—è (–Ω–µ –±–æ–ª–µ–µ 10
    –ø–æ–ø—ã—Ç–æ–∫) –¥–æ –ø–æ–ª—É—á–µ–Ω–∏—è —Å—Ç–∞—Ç—É—Å–∞ `CONFIRMED` –∏–ª–∏ `FAILED`.


    ---


    # –°—Ç–∞—Ç—É—Å–Ω–∞—è –º–æ–¥–µ–ª—å


    –¢—Ä–∞–Ω–∑–∞–∫—Ü–∏—è –º–æ–∂–µ—Ç –Ω–∞—Ö–æ–¥–∏—Ç—å—Å—è –≤ –æ–¥–Ω–æ–º –∏–∑ —Ç—Ä—ë—Ö —Å—Ç–∞—Ç—É—Å–æ–≤.


    <a href='/img/merchant-api/merchant-state-model.png' target='_blank'><img
    style="display: block; margin: 0 auto; max-width:40%; height:auto;"
    src='/img/merchant-api/merchant-state-model.png'/></a>.


    –ï—Å–ª–∏ –≤—ã –Ω–µ –ø–æ–ª—É—á–∏–ª–∏ –∑–∞–ø—Ä–æ—Å —Å –ø–æ–¥—Ç–≤–µ—Ä–∂–¥–µ–Ω–∏–µ–º —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –≤ —Ç–µ—á–µ–Ω–∏–µ 30 –º–∏–Ω—É—Ç —Å
    –º–æ–º–µ–Ω—Ç–∞ –µ—ë —Å–æ–∑–¥–∞–Ω–∏—è, —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏—è —Å—á–∏—Ç–∞–µ—Ç—Å—è –Ω–µ—É—Å–ø–µ—à–Ω–æ–π. –í —ç—Ç–æ–º —Å–ª—É—á–∞–µ
    –ø–µ—Ä–µ–≤–µ–¥–∏—Ç–µ —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏—é –Ω–∞ —Å–≤–æ–µ–π —Å—Ç–æ—Ä–æ–Ω–µ –≤ —Å—Ç–∞—Ç—É—Å `FAILED`.


    ---


    # –§–æ—Ä–º–∞—Ç –∑–∞–ø—Ä–æ—Å–æ–≤


    Uzum Bank –∏—Å–ø–æ–ª—å–∑—É–µ—Ç –ø—Ä–æ—Ç–æ–∫–æ–ª HTTPS –¥–ª—è –¥–æ—Å—Ç–∞–≤–∫–∏ –≤–µ–±—Ö—É–∫–æ–≤ –ø–∞—Ä—Ç–Ω—ë—Ä—É. –ó–∞–ø—Ä–æ—Å—ã
    –æ—Ç–ø—Ä–∞–≤–ª—è—é—Ç—Å—è –º–µ—Ç–æ–¥–æ–º `POST` –≤ —Ñ–æ—Ä–º–∞—Ç–µ `application/json`, –∏ –æ—Ç–≤–µ—Ç—ã —Ç–∞–∫–∂–µ
    –æ–∂–∏–¥–∞—é—Ç—Å—è –≤ —Ñ–æ—Ä–º–∞—Ç–µ `application/json`.


    ---


    # –ê–≤—Ç–æ—Ä–∏–∑–∞—Ü–∏—è


    –ê–≤—Ç–æ—Ä–∏–∑–∞—Ü–∏—è –æ—Å—É—â–µ—Å—Ç–≤–ª—è–µ—Ç—Å—è —á–µ—Ä–µ–∑ HTTP –∑–∞–≥–æ–ª–æ–≤–æ–∫ <a
    href="https://developer.mozilla.org/ru/docs/Web/HTTP/Headers/Authorization"
    target="_blank">Authorization</a>, –∫–æ—Ç–æ—Ä—ã–π –Ω–µ–æ–±—Ö–æ–¥–∏–º–æ –≤–∫–ª—é—á–∞—Ç—å –≤ –∫–∞–∂–¥—ã–π
    –∑–∞–ø—Ä–æ—Å. –î–ª—è —Ñ–æ—Ä–º–∏—Ä–æ–≤–∞–Ω–∏—è –∑–∞–≥–æ–ª–æ–≤–∫–∞ –∏—Å–ø–æ–ª—å–∑—É–µ—Ç—Å—è —Å—Ö–µ–º–∞ ¬´Basic¬ª –∏ –¥–∞–Ω–Ω—ã–µ
    –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—è, –∑–∞–∫–æ–¥–∏—Ä–æ–≤–∞–Ω–Ω—ã–µ –≤ —Ñ–æ—Ä–º–∞—Ç–µ <a
    href="https://developer.mozilla.org/ru/docs/Glossary/Base64"
    target="_blank">base64</a>: `Authorization: Basic <–¥–∞–Ω–Ω—ã–µ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—è>`.


    –î–ª—è —Ñ–æ—Ä–º–∏—Ä–æ–≤–∞–Ω–∏—è –∑–∞–≥–æ–ª–æ–≤–∫–∞:


    1. –°—Ñ–æ—Ä–º–∏—Ä—É–π—Ç–µ —Å—Ç—Ä–æ–∫—É –∏–∑ –ª–æ–≥–∏–Ω–∞ –∏ –ø–∞—Ä–æ–ª—è, —Ä–∞–∑–¥–µ–ª—ë–Ω–Ω—ã—Ö –¥–≤–æ–µ—Ç–æ—á–∏–µ–º, –Ω–∞–ø—Ä–∏–º–µ—Ä:
    "myLogin:myPassword";

    1. –ó–∞–∫–æ–¥–∏—Ä—É–π—Ç–µ —Å—Ç—Ä–æ–∫—É –≤ base64, –ø—Ä–∏–º–µ—Ä —Ä–µ–∑—É–ª—å—Ç–∞—Ç–∞ YWxhZGRpbjpvcGVuc2VzYW1l;

    1. –í—Å—Ç–∞–≤—å—Ç–µ —Ä–µ–∑—É–ª—å—Ç–∞—Ç –≤ –∑–∞–≥–æ–ª–æ–≤–æ–∫; –£–±–µ–¥–∏—Ç–µ—Å—å, —á—Ç–æ –º–µ–∂–¥—É —Å–ª–æ–≤–æ–º "Basic" –∏
    –∑–∞–∫–æ–¥–∏—Ä–æ–≤–∞–Ω–Ω—ã–º–∏ —É—á–µ—Ç–Ω—ã–º–∏ –¥–∞–Ω–Ω—ã–º–∏ –µ—Å—Ç—å –ø—Ä–æ–±–µ–ª.


    –¢–∞–∫–∏–º –æ–±—Ä–∞–∑–æ–º, –∑–∞–≥–æ–ª–æ–≤–æ–∫ –±—É–¥–µ—Ç –∏–º–µ—Ç—å –≤–∏–¥:


    | Header      | Value                        |

    |--------------------|------------------------------|

    | Authorization | Basic YWxhZGRpbjpvcGVuc2VzYW1l    |


    ---
tags:
  - name: –í–µ–±—Ö—É–∫–∏
    description: >
      –ó–∞–ø—Ä–æ—Å—ã, –∫–æ—Ç–æ—Ä—ã–µ Uzum Bank –æ—Ç–ø—Ä–∞–≤–ª—è–µ—Ç –ø–∞—Ä—Ç–Ω–µ—Ä—É –≤ –ø—Ä–æ—Ü–µ—Å—Å–µ –ø—Ä–æ–≤–µ–¥–µ–Ω–∏—è
      –ø–ª–∞—Ç–µ–∂–∞ —Å–æ–≥–ª–∞—Å–Ω–æ –ø—Ä–æ—Ç–æ–∫–æ–ª—É Merchant API.
security:
  - BasicAuth: []
webhooks:
  /check:
    post:
      summary: –ü—Ä–æ–≤–µ—Ä–∫–∞ –≤–æ–∑–º–æ–∂–Ω–æ—Å—Ç–∏ –ø—Ä–æ–≤–µ–¥–µ–Ω–∏—è –ø–ª–∞—Ç–µ–∂–∞
      description: >
        –í–µ–±—Ö—É–∫ `/check` –∏—Å–ø–æ–ª—å–∑—É–µ—Ç—Å—è –¥–ª—è –ø—Ä–æ–≤–µ—Ä–∫–∏ –≤–æ–∑–º–æ–∂–Ω–æ—Å—Ç–∏ –ø—Ä–æ–≤–µ–¥–µ–Ω–∏—è –ø–ª–∞—Ç–µ–∂–∞
        –∏ –ø–æ–ª—É—á–µ–Ω–∏—è –¥–æ–ø–æ–ª–Ω–∏—Ç–µ–ª—å–Ω–æ–π –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏–∏ –æ –ø–ª–∞—Ç–µ–∂–µ –∏–ª–∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª–µ.
      tags:
        - –í–µ–±—Ö—É–∫–∏
      operationId: check
      requestBody:
        $ref: '#/components/requestBodies/CheckRequest'
      responses:
        '200':
          $ref: '#/components/responses/CheckResponseSuccess'
        '400':
          $ref: '#/components/responses/CheckResponseError'
  /create:
    post:
      summary: –°–æ–∑–¥–∞–Ω–∏–µ —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞
      description: >
        –í–µ–±—Ö—É–∫ `/create` –∏—Å–ø–æ–ª—å–∑—É–µ—Ç—Å—è –¥–ª—è —Å–æ–∑–¥–∞–Ω–∏—è —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞ –≤ —Å–∏—Å—Ç–µ–º–µ
        –ø–∞—Ä—Ç–Ω–µ—Ä–∞.
      tags:
        - –í–µ–±—Ö—É–∫–∏
      operationId: create
      requestBody:
        $ref: '#/components/requestBodies/CreateRequest'
      responses:
        '200':
          $ref: '#/components/responses/CreateResponseSuccess'
        '400':
          $ref: '#/components/responses/CreateResponseError'
  /confirm:
    post:
      summary: –ü–æ–¥—Ç–≤–µ—Ä–∂–¥–µ–Ω–∏–µ —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞
      description: >
        –í–µ–±—Ö—É–∫ `/confirm` –∏—Å–ø–æ–ª—å–∑—É–µ—Ç—Å—è –¥–ª—è –ø–æ–¥—Ç–≤–µ—Ä–∂–¥–µ–Ω–∏—è —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞
        –ø–æ—Å–ª–µ —É—Å–ø–µ—à–Ω–æ–π –æ–ø–ª–∞—Ç—ã —Å–µ—Ä–≤–∏—Å–∞.
      tags:
        - –í–µ–±—Ö—É–∫–∏
      operationId: confirm
      requestBody:
        $ref: '#/components/requestBodies/ConfirmRequest'
      responses:
        '200':
          $ref: '#/components/responses/ConfirmResponseSuccess'
        '400':
          $ref: '#/components/responses/ConfirmResponseError'
  /reverse:
    post:
      summary: –û—Ç–º–µ–Ω–∞ —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞
      description: >
        –í–µ–±—Ö—É–∫ `/reverse` –∏—Å–ø–æ–ª—å–∑—É–µ—Ç—Å—è –¥–ª—è –æ—Ç–º–µ–Ω—ã —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞ –≤ —Å–∏—Å—Ç–µ–º–µ
        –ø–∞—Ä—Ç–Ω–µ—Ä–∞.
      tags:
        - –í–µ–±—Ö—É–∫–∏
      operationId: reverse
      requestBody:
        $ref: '#/components/requestBodies/ReverseRequest'
      responses:
        '200':
          $ref: '#/components/responses/ReverseResponseSuccess'
        '400':
          $ref: '#/components/responses/ReverseResponseError'
  /status:
    post:
      summary: –ü—Ä–æ–≤–µ—Ä–∫–∞ —Å—Ç–∞—Ç—É—Å–∞ —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞
      description: >
        –í–µ–±—Ö—É–∫ `/status` –∏—Å–ø–æ–ª—å–∑—É–µ—Ç—Å—è –¥–ª—è –ø—Ä–æ–≤–µ—Ä–∫–∏ —Å—Ç–∞—Ç—É—Å–∞ —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞ –≤
        —Å–∏—Å—Ç–µ–º–µ –ø–∞—Ä—Ç–Ω–µ—Ä–∞.
      tags:
        - –í–µ–±—Ö—É–∫–∏
      operationId: status
      requestBody:
        $ref: '#/components/requestBodies/StatusRequest'
      responses:
        '200':
          $ref: '#/components/responses/StatusResponseSuccess'
        '400':
          $ref: '#/components/responses/StatusResponseError'
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  requestBodies:
    CheckRequest:
      description: |
        JSON –æ–±—ä–µ–∫—Ç —Å –ø–∞—Ä–∞–º–µ—Ç—Ä–∞–º–∏ –∑–∞–ø—Ä–æ—Å–∞.
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CheckRequest'
    CreateRequest:
      description: |
        JSON –æ–±—ä–µ–∫—Ç —Å –ø–∞—Ä–∞–º–µ—Ç—Ä–∞–º–∏ –∑–∞–ø—Ä–æ—Å–∞.
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateRequest'
    ConfirmRequest:
      description: |
        JSON –æ–±—ä–µ–∫—Ç —Å –ø–∞—Ä–∞–º–µ—Ç—Ä–∞–º–∏ –∑–∞–ø—Ä–æ—Å–∞.
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ConfirmRequest'
    ReverseRequest:
      description: |
        JSON –æ–±—ä–µ–∫—Ç —Å –ø–∞—Ä–∞–º–µ—Ç—Ä–∞–º–∏ –∑–∞–ø—Ä–æ—Å–∞.
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ReverseRequest'
    StatusRequest:
      description: |
        JSON –æ–±—ä–µ–∫—Ç —Å –ø–∞—Ä–∞–º–µ—Ç—Ä–∞–º–∏ –∑–∞–ø—Ä–æ—Å–∞.
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/StatusRequest'
  responses:
    CheckResponseSuccess:
      description: |
        –£—Å–ø–µ—à–Ω—ã–π –æ—Ç–≤–µ—Ç.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Check'
    CheckResponseError:
      description: |
        –û—Ç–≤–µ—Ç —Å –æ—à–∏–±–∫–æ–π / Xato javob
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CheckError'
    CreateResponseSuccess:
      description: |
        –£—Å–ø–µ—à–Ω—ã–π –æ—Ç–≤–µ—Ç.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Create'
    CreateResponseError:
      description: |
        –û—Ç–≤–µ—Ç —Å –æ—à–∏–±–∫–æ–π / Xato javob
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateError'
    ConfirmResponseSuccess:
      description: |
        –£—Å–ø–µ—à–Ω—ã–π –æ—Ç–≤–µ—Ç.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Confirm'
    ConfirmResponseError:
      description: |
        –û—Ç–≤–µ—Ç —Å –æ—à–∏–±–∫–æ–π / Xato javob
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ConfirmError'
    ReverseResponseSuccess:
      description: |
        –£—Å–ø–µ—à–Ω—ã–π –æ—Ç–≤–µ—Ç.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Reverse'
    ReverseResponseError:
      description: |
        –û—Ç–≤–µ—Ç —Å –æ—à–∏–±–∫–æ–π / Xato javob
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ReverseError'
    StatusResponseSuccess:
      description: |
        –£—Å–ø–µ—à–Ω—ã–π –æ—Ç–≤–µ—Ç.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Status'
    StatusResponseError:
      description: |
        –û—Ç–≤–µ—Ç —Å –æ—à–∏–±–∫–æ–π / Xato javob
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/StatusError'
  schemas:
    CheckRequest:
      type: object
      properties:
        serviceId:
          description: |
            –ò–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä —Å–µ—Ä–≤–∏—Å–∞ –∑–∞ –∫–æ—Ç–æ—Ä—ã–π –ø—Ä–æ–∏–∑–≤–æ–¥–∏—Ç—Å—è –æ–ø–ª–∞—Ç–∞.
          type: integer
          format: int64
          example: 101202
        timestamp:
          description: |
            –í—Ä–µ–º—è –æ—Ç–ø—Ä–∞–≤–∫–∏ –∑–∞–ø—Ä–æ—Å–∞ (unix timestamp –≤ –º–∏–ª–ª–∏—Å–µ–∫—É–Ω–¥–∞—Ö).
          type: integer
          format: int64
          example: 1698361456728
        params:
          description: >
            –û–±—ä–µ–∫—Ç —Å –¥–æ–ø–æ–ª–Ω–∏—Ç–µ–ª—å–Ω—ã–º–∏ —Å–≤–æ–π—Å—Ç–≤–∞–º–∏ –ø–ª–∞—Ç–µ–∂–∞, –Ω–∞–ø—Ä–∏–º–µ—Ä, –Ω–æ–º–µ—Ä
            –ª–∏—Ü–µ–≤–æ–≥–æ —Å—á—ë—Ç–∞ `account`.
          type: object
          example:
            account: 123456789
      required:
        - serviceId
        - timestamp
        - params
    Check:
      type: object
      properties:
        serviceId:
          description: |
            –ò–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä —Å–µ—Ä–≤–∏—Å–∞ –∑–∞ –∫–æ—Ç–æ—Ä—ã–π –ø—Ä–æ–∏–∑–≤–æ–¥–∏—Ç—Å—è –æ–ø–ª–∞—Ç–∞.
          type: integer
          format: int64
          example: 101202
        timestamp:
          description: >
            –í—Ä–µ–º—è –ø—Ä–æ–≤–µ—Ä–∫–∏ –≤–æ–∑–º–æ–∂–Ω–æ—Å—Ç–∏ –ø—Ä–æ–≤–µ–¥–µ–Ω–∏—è –ø–ª–∞—Ç–µ–∂–∞ (unix timestamp –≤
            –º–∏–ª–ª–∏—Å–µ–∫—É–Ω–¥–∞—Ö).
          type: integer
          format: int64
          example: 1698361457021
        status:
          description: |
            –°—Ç–∞—Ç—É—Å –ø—Ä–æ–≤–µ—Ä–∫–∏ –ø–ª–∞—Ç–µ–∂–∞.
          type: string
          enum:
            - OK
          example: OK
        data:
          description: >
            –î–∞–Ω–Ω—ã–µ –æ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª–µ –∏ –ø–ª–∞—Ç–µ–∂–µ (–º–æ–∂–µ—Ç –±—ã—Ç—å –ø—É—Å—Ç—ã–º –æ–±—ä–µ–∫—Ç–æ–º). 

            –û–±—ä–µ–∫—Ç `data` —Å–æ—Å—Ç–æ–∏—Ç –∏–∑ –ø–∞—Ä –∫–ª—é—á-–∑–Ω–∞—á–µ–Ω–∏–µ. –ù–∞–∑–≤–∞–Ω–∏–µ –∫–ª—é—á–∞ —è–≤–ª—è–µ—Ç—Å—è
            –ø—Ä–æ–∏–∑–≤–æ–ª—å–Ω—ã–º, –Ω–∞–ø—Ä–∏–º–µ—Ä: `account` –∏–ª–∏ `fio`.

            –ó–Ω–∞—á–µ–Ω–∏–µ–º —è–≤–ª—è–µ—Ç—Å—è –æ–±—ä–µ–∫—Ç —Å –µ–¥–∏–Ω—Å—Ç–≤–µ–Ω–Ω—ã–º —Å–≤–æ–π—Å—Ç–≤–æ–º `value` (—Ç–∏–ø
            `string`).
          type: object
          example:
            account:
              value: '123456789'
            fio:
              value: –ò–≤–∞–Ω–æ–≤ –ò–≤–∞–Ω –ò–≤–∞–Ω–æ–≤–∏—á
      required:
        - serviceId
        - timestamp
        - status
    CheckError:
      type: object
      properties:
        serviceId:
          description: |
            –ò–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä —Å–µ—Ä–≤–∏—Å–∞ –∑–∞ –∫–æ—Ç–æ—Ä—ã–π –ø—Ä–æ–∏–∑–≤–æ–¥–∏—Ç—Å—è –æ–ø–ª–∞—Ç–∞.
          type: integer
          format: int64
          example: 101202
        timestamp:
          description: >
            –í—Ä–µ–º—è –ø—Ä–æ–≤–µ—Ä–∫–∏ –≤–æ–∑–º–æ–∂–Ω–æ—Å—Ç–∏ –ø—Ä–æ–≤–µ–¥–µ–Ω–∏—è –ø–ª–∞—Ç–µ–∂–∞ (unix timestamp –≤
            –º–∏–ª–ª–∏—Å–µ–∫—É–Ω–¥–∞—Ö).
          type: integer
          format: int64
          example: 1698361457021
        status:
          description: |
            –°—Ç–∞—Ç—É—Å –ø—Ä–æ–≤–µ—Ä–∫–∏ –ø–ª–∞—Ç–µ–∂–∞.
          type: string
          enum:
            - FAILED
          example: FAILED
        errorCode:
          description: >
            –ö–æ–¥ –æ—à–∏–±–∫–∏ –ø—Ä–æ–≤–µ—Ä–∫–∏ –≤–æ–∑–º–æ–∂–Ω–æ—Å—Ç–∏ –ø—Ä–æ–≤–µ–¥–µ–Ω–∏—è –ø–ª–∞—Ç–µ–∂–∞.


            –ö–æ–¥ –æ—à–∏–±–∫–∏ | –û–ø–∏—Å–∞–Ω–∏–µ –æ—à–∏–±–∫–∏ | –ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–∏

            -|-|-

            10001 | –î–æ—Å—Ç—É–ø –∑–∞–ø—Ä–µ—â–µ–Ω | –û—à–∏–±–∫–∞ –∞–≤—Ç–æ—Ä–∏–∑–∞—Ü–∏–∏ 

            10002 | –û—à–∏–±–∫–∞ –ø–∞—Ä—Å–∏–Ω–≥–∞ JSON –æ–±—ä–µ–∫—Ç–∞ —Å –ø–∞—Ä–∞–º–µ—Ç—Ä–∞–º–∏ –∑–∞–ø—Ä–æ—Å–∞

            10003 | –ù–µ–¥–æ–ø—É—Å—Ç–∏–º–∞—è –æ–ø–µ—Ä–∞—Ü–∏—è | –ù–µ–≤–µ—Ä–Ω—ã–π HTTP –º–µ—Ç–æ–¥

            10005 | –û—Ç—Å—É—Ç—Å—Ç–≤—É—é—Ç –æ–±—è–∑–∞—Ç–µ–ª—å–Ω—ã–µ –ø–∞—Ä–∞–º–µ—Ç—Ä—ã –≤ –∑–∞–ø—Ä–æ—Å–µ 

            10006 | –ù–µ–≤–µ—Ä–Ω—ã–π `serviceId` 

            10007 | –î–æ–ø–æ–ª–Ω–∏—Ç–µ–ª—å–Ω—ã–π –∞—Ç—Ä–∏–±—É—Ç –ø–ª–∞—Ç–µ–∂–∞ –Ω–µ –Ω–∞–π–¥–µ–Ω | –ù–∞–ø—Ä–∏–º–µ—Ä: –Ω–æ–º–µ—Ä
            –ª–∏—Ü–µ–≤–æ–≥–æ —Å—á–µ—Ç–∞, —Ç–µ–ª–µ—Ñ–æ–Ω–∞ –∏–ª–∏ –∑–∞–∫–∞–∑–∞ / Masalan: shaxsiy hisob raqami,
            telefon yoki buyurtma raqami

            10008 | –ü–ª–∞—Ç–µ–∂ —É–∂–µ –æ–ø–ª–∞—á–µ–Ω | –î–ª—è —É–∫–∞–∑–∞–Ω–Ω—ã—Ö –¥–æ–ø–æ–ª–Ω–∏—Ç–µ–ª—å–Ω—ã—Ö –∞—Ç—Ä–∏–±—É—Ç–æ–≤ 

            10009 | –ü–ª–∞—Ç–µ–∂ –æ—Ç–º–µ–Ω–µ–Ω| –î–ª—è —É–∫–∞–∑–∞–Ω–Ω—ã—Ö –¥–æ–ø–æ–ª–Ω–∏—Ç–µ–ª—å–Ω—ã—Ö –∞—Ç—Ä–∏–±—É—Ç–æ–≤ 

            99999 | –û—à–∏–±–∫–∞ –ø—Ä–æ–≤–µ—Ä–∫–∏ –¥–∞–Ω–Ω—ã—Ö | –°–µ—Ä–≤–∏—Å –Ω–µ–¥–æ—Å—Ç—É–ø–µ–Ω, –ø–æ–≤—Ç–æ—Ä–∏—Ç–µ
            –ø–æ–ø—ã—Ç–∫—É –ø–æ–∑–∂–µ 
          type: string
          example: '10007'
      required:
        - errorCode
    CreateRequest:
      type: object
      properties:
        serviceId:
          description: |
            –ò–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä —Å–µ—Ä–≤–∏—Å–∞ –∑–∞ –∫–æ—Ç–æ—Ä—ã–π –ø—Ä–æ–∏–∑–≤–æ–¥–∏—Ç—Å—è –æ–ø–ª–∞—Ç–∞.
          type: integer
          format: int64
          example: 101202
        timestamp:
          description: |
            –í—Ä–µ–º—è –æ—Ç–ø—Ä–∞–≤–∫–∏ –∑–∞–ø—Ä–æ—Å–∞ (unix timestamp –≤ –º–∏–ª–ª–∏—Å–µ–∫—É–Ω–¥–∞—Ö).
          type: integer
          format: int64
          example: 1698361456728
        transId:
          description: |
            –ò–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞, —Å–æ–∑–¥–∞–Ω–Ω–æ–π –≤ Uzum Bank.
          type: string
          format: uuid
          example: 5c398d7e-76b6-11ee-96da-f3a095c6289d
        params:
          description: >
            –û–±—ä–µ–∫—Ç —Å –¥–æ–ø–æ–ª–Ω–∏—Ç–µ–ª—å–Ω—ã–º–∏ —Å–≤–æ–π—Å—Ç–≤–∞–º–∏ –ø–ª–∞—Ç–µ–∂–∞, –Ω–∞–ø—Ä–∏–º–µ—Ä, –Ω–æ–º–µ—Ä
            –ª–∏—Ü–µ–≤–æ–≥–æ —Å—á—ë—Ç–∞ `account`.
          type: object
          example:
            account: 123456789
        amount:
          description: |
            –°—É–º–º–∞ –ø–ª–∞—Ç–µ–∂–∞ –≤ —Ç–∏–π–∏–Ω–∞—Ö.
          type: integer
          format: int64
          example: 2500000
      required:
        - serviceId
        - timestamp
        - transId
        - params
        - amount
    Create:
      type: object
      properties:
        serviceId:
          description: |
            –ò–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä —Å–µ—Ä–≤–∏—Å–∞ –∑–∞ –∫–æ—Ç–æ—Ä—ã–π –ø—Ä–æ–∏–∑–≤–æ–¥–∏—Ç—Å—è –æ–ø–ª–∞—Ç–∞.
          type: integer
          format: int64
          example: 101202
        transId:
          description: |
            –ò–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞, —Å–æ–∑–¥–∞–Ω–Ω–æ–π –≤ Uzum Bank.
          type: string
          format: uuid
          example: 5c398d7e-76b6-11ee-96da-f3a095c6289d
        status:
          description: |
            –°—Ç–∞—Ç—É—Å —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞.

            To'lov tranzaksiya holati.
          type: string
          enum:
            - CREATED
          example: CREATED
        transTime:
          description: |
            –í—Ä–µ–º—è —Å–æ–∑–¥–∞–Ω–∏—è —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞ (unix timestamp –≤ –º–∏–ª–ª–∏—Å–µ–∫—É–Ω–¥–∞—Ö).
          type: integer
          format: int64
          example: 1698361458054
        data:
          description: >
            –î–∞–Ω–Ω—ã–µ –æ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª–µ –∏ —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞ (–º–æ–∂–µ—Ç –±—ã—Ç—å –ø—É—Å—Ç—ã–º
            –æ–±—ä–µ–∫—Ç–æ–º). 

            –û–±—ä–µ–∫—Ç `data` —Å–æ—Å—Ç–æ–∏—Ç –∏–∑ –ø–∞—Ä –∫–ª—é—á-–∑–Ω–∞—á–µ–Ω–∏–µ. –ù–∞–∑–≤–∞–Ω–∏–µ –∫–ª—é—á–∞ —è–≤–ª—è–µ—Ç—Å—è
            –ø—Ä–æ–∏–∑–≤–æ–ª—å–Ω—ã–º, –Ω–∞–ø—Ä–∏–º–µ—Ä: `account` –∏–ª–∏ `fio`.

            –ó–Ω–∞—á–µ–Ω–∏–µ–º —è–≤–ª—è–µ—Ç—Å—è –æ–±—ä–µ–∫—Ç —Å –µ–¥–∏–Ω—Å—Ç–≤–µ–Ω–Ω—ã–º —Å–≤–æ–π—Å—Ç–≤–æ–º `value` (—Ç–∏–ø
            `string`).
          type: object
          example:
            account:
              value: '123456789'
            fio:
              value: –ò–≤–∞–Ω–æ–≤ –ò–≤–∞–Ω –ò–≤–∞–Ω–æ–≤–∏—á
        amount:
          description: |
            –°—É–º–º–∞ –ø–ª–∞—Ç–µ–∂–∞ –≤ —Ç–∏–π–∏–Ω–∞—Ö.
          type: integer
          format: int64
          example: 2500000
      required:
        - serviceId
        - transId
        - status
        - transTime
        - amount
    CreateError:
      type: object
      properties:
        serviceId:
          description: |
            –ò–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä —Å–µ—Ä–≤–∏—Å–∞ –∑–∞ –∫–æ—Ç–æ—Ä—ã–π –ø—Ä–æ–∏–∑–≤–æ–¥–∏—Ç—Å—è –æ–ø–ª–∞—Ç–∞.
          type: integer
          format: int64
          example: 101202
        transId:
          description: |
            –ò–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞, —Å–æ–∑–¥–∞–Ω–Ω–æ–π –≤ Uzum Bank.
          type: string
          format: uuid
          example: 5c398d7e-76b6-11ee-96da-f3a095c6289d
        status:
          description: |
            –°—Ç–∞—Ç—É—Å —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞.
          type: string
          enum:
            - FAILED
          example: FAILED
        transTime:
          description: |
            –í—Ä–µ–º—è —Å–æ–∑–¥–∞–Ω–∏—è —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞ (unix timestamp –≤ –º–∏–ª–ª–∏—Å–µ–∫—É–Ω–¥–∞—Ö).
          type: integer
          format: int64
          example: 1698361458054
        errorCode:
          description: >
            –ö–æ–¥ –æ—à–∏–±–∫–∏ —Å–æ–∑–¥–∞–Ω–∏—è —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞.


            –ö–æ–¥ –æ—à–∏–±–∫–∏ | –û–ø–∏—Å–∞–Ω–∏–µ –æ—à–∏–±–∫–∏ | –ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–∏

            -|-|-

            10001 | –î–æ—Å—Ç—É–ø –∑–∞–ø—Ä–µ—â–µ–Ω  | –û—à–∏–±–∫–∞ –∞–≤—Ç–æ—Ä–∏–∑–∞—Ü–∏–∏

            10002 | –û—à–∏–±–∫–∞ –ø–∞—Ä—Å–∏–Ω–≥–∞ JSON –æ–±—ä–µ–∫—Ç–∞ —Å –ø–∞—Ä–∞–º–µ—Ç—Ä–∞–º–∏ –∑–∞–ø—Ä–æ—Å–∞

            10003 | –ù–µ–¥–æ–ø—É—Å—Ç–∏–º–∞—è –æ–ø–µ—Ä–∞—Ü–∏—è | –ù–µ–≤–µ—Ä–Ω—ã–π HTTP –º–µ—Ç–æ–¥ 

            10005 | –û—Ç—Å—É—Ç—Å—Ç–≤—É—é—Ç –æ–±—è–∑–∞—Ç–µ–ª—å–Ω—ã–µ –ø–∞—Ä–∞–º–µ—Ç—Ä—ã –≤ –∑–∞–ø—Ä–æ—Å–µ 

            10006 | –ù–µ–≤–µ—Ä–Ω—ã–π `serviceId` 

            10007 | –î–æ–ø–æ–ª–Ω–∏—Ç–µ–ª—å–Ω—ã–π –∞—Ç—Ä–∏–±—É—Ç –ø–ª–∞—Ç–µ–∂–∞ –Ω–µ –Ω–∞–π–¥–µ–Ω | –ù–∞–ø—Ä–∏–º–µ—Ä: –Ω–æ–º–µ—Ä
            –ª–∏—Ü–µ–≤–æ–≥–æ —Å—á–µ—Ç–∞, —Ç–µ–ª–µ—Ñ–æ–Ω–∞ –∏–ª–∏ –∑–∞–∫–∞–∑–∞ 

            10008 | –ü–ª–∞—Ç–µ–∂ —É–∂–µ –æ–ø–ª–∞—á–µ–Ω | –î–ª—è —É–∫–∞–∑–∞–Ω–Ω—ã—Ö –¥–æ–ø–æ–ª–Ω–∏—Ç–µ–ª—å–Ω—ã—Ö –∞—Ç—Ä–∏–±—É—Ç–æ–≤

            10009 | –ü–ª–∞—Ç–µ–∂ –æ—Ç–º–µ–Ω–µ–Ω | –î–ª—è —É–∫–∞–∑–∞–Ω–Ω—ã—Ö –¥–æ–ø–æ–ª–Ω–∏—Ç–µ–ª—å–Ω—ã—Ö –∞—Ç—Ä–∏–±—É—Ç–æ–≤

            10010 | –¢—Ä–∞–Ω–∑–∞–∫—Ü–∏—è —Å —É–∫–∞–∑–∞–Ω–Ω—ã–º –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä–æ–º `transId` —É–∂–µ
            —Å–æ–∑–¥–∞–Ω–∞ 

            10011 | –ù–µ–≤–µ—Ä–Ω–∞—è —Å—É–º–º–∞ 

            10012 | –°—É–º–º–∞ –æ–ø–ª–∞—Ç—ã –Ω–∏–∂–µ –º–∏–Ω–∏–º–∞–ª—å–Ω–æ–π

            10013 | –°—É–º–º–∞ –æ–ø–ª–∞—Ç—ã –ø—Ä–µ–≤—ã—à–∞–µ—Ç –º–∞–∫—Å–∏–º–∞–ª—å–Ω—É—é 

            99999 | –û—à–∏–±–∫–∞ –ø—Ä–æ–≤–µ—Ä–∫–∏ –¥–∞–Ω–Ω—ã—Ö | –°–µ—Ä–≤–∏—Å –Ω–µ–¥–æ—Å—Ç—É–ø–µ–Ω, –ø–æ–≤—Ç–æ—Ä–∏—Ç–µ
            –ø–æ–ø—ã—Ç–∫—É –ø–æ–∑–∂–µ
          type: string
          example: '10013'
      required:
        - errorCode
    ConfirmRequest:
      type: object
      properties:
        serviceId:
          description: |
            –ò–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä —Å–µ—Ä–≤–∏—Å–∞ –∑–∞ –∫–æ—Ç–æ—Ä—ã–π –ø—Ä–æ–∏–∑–≤–æ–¥–∏—Ç—Å—è –æ–ø–ª–∞—Ç–∞.
          type: integer
          format: int64
          example: 101202
        timestamp:
          description: |
            –í—Ä–µ–º—è –æ—Ç–ø—Ä–∞–≤–∫–∏ –∑–∞–ø—Ä–æ—Å–∞ (unix timestamp –≤ –º–∏–ª–ª–∏—Å–µ–∫—É–Ω–¥–∞—Ö).
          type: integer
          format: int64
          example: 1698361456728
        transId:
          description: |
            –ò–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞, —Å–æ–∑–¥–∞–Ω–Ω–æ–π –≤ Uzum Bank.
          type: string
          format: uuid
          example: 5c398d7e-76b6-11ee-96da-f3a095c6289d
        paymentSource:
          description: >
            –ü—Ä–∏–∑–Ω–∞–∫ –∏—Å—Ç–æ—á–Ω–∏–∫–∞ –æ–ø–ª–∞—Ç: UZCARD, HUMO, VISA, MASTERCARD,
            VISA_DOMESTIC, MASTERCARD_DOMESTIC, INSTALLMENT, CASHBACK, ACCOUNT,
            WALLET, VISAUZS, UZUM_DEBIT_VISA.
          type: string
          format: enum
          example: INSTALLMENT
        tariff:
          description: >
            `tariff` –¥–æ—Å—Ç—É–ø–µ–Ω, –µ—Å–ª–∏ —Å–∏–º–≤–æ–ª –∏—Å—Ç–æ—á–Ω–∏–∫–∞ –ø–ª–∞—Ç–µ–∂–∞ ‚Äî `INSTALLMENT` –≤
            –ø—Ä–æ—Ç–∏–≤–Ω–æ–º —Å–ª—É—á–∞–µ ‚Äî `null`:  "003" –∏–ª–∏ "15-0-4" –∏–ª–∏ `null`
          type: string
          format: string
          example: '003'
        processingReferenceNumber:
          description: >
            –°–ø—Ä–∞–≤–æ—á–Ω—ã–π –Ω–æ–º–µ—Ä –ø—Ä–æ—Ü–µ—Å—Å–∏–Ω–≥–∞. –î–∞–Ω–Ω–æ–µ –ø–æ–ª–µ –æ—Ç–ø—Ä–∞–≤–ª—è–µ—Ç—Å—è —Ç–æ–ª—å–∫–æ –ø—Ä–∏
            –æ–ø–ª–∞—Ç–µ –∫–∞—Ä—Ç–∞–º–∏: Uzcard, Humo, Visa Uzum Bank, Visa Kapital Bank. –í
            –ø—Ä–æ—Ç–∏–≤–Ω–æ–º —Å–ª—É—á–∞–µ –∑–Ω–∞—á–µ–Ω–∏–µ —ç—Ç–æ–≥–æ –ø–æ–ª—è –±—É–¥–µ—Ç `null`.
          type: string
          format: string
          example: '000'
        phone:
          description: |
            –ù–æ–º–µ—Ä —Ç–µ–ª–µ—Ñ–æ–Ω–∞ –∫–ª–∏–µ–Ω—Ç–∞.
          type: string
          format: string
          example: '998901234567'
        cardType:
          description: >
            –¢–∏–ø –±–∞–Ω–∫–æ–≤—Å–∫–æ–π –∫–∞—Ä—Ç—ã –∫–ª–∏–µ–Ω—Ç–∞ (1 - –∫–æ—Ä–ø–æ—Ä–∞—Ç–∏–≤–Ω–∞—è –∫–∞—Ä—Ç–∞, 2 - –∫–∞—Ä—Ç–∞
            —Ñ–∏–∑–∏—á–µ—Å–∫–æ–≥–æ –ª–∏—Ü–∞).
          type: integer
          format: int32
          example: 2
      required:
        - serviceId
        - timestamp
        - transId
        - paymentSource
        - phone
    Confirm:
      type: object
      properties:
        serviceId:
          description: |
            –ò–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä —Å–µ—Ä–≤–∏—Å–∞ –∑–∞ –∫–æ—Ç–æ—Ä—ã–π –ø—Ä–æ–∏–∑–≤–æ–¥–∏—Ç—Å—è –æ–ø–ª–∞—Ç–∞.
          type: integer
          format: int64
          example: 101202
        transId:
          description: |
            –ò–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞, —Å–æ–∑–¥–∞–Ω–Ω–æ–π –≤ Uzum Bank.
          type: string
          format: uuid
          example: 5c398d7e-76b6-11ee-96da-f3a095c6289d
        status:
          description: |
            –°—Ç–∞—Ç—É—Å —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞.
          type: string
          enum:
            - CONFIRMED
          example: CONFIRMED
        confirmTime:
          description: >
            –í—Ä–µ–º—è –ø–æ–¥—Ç–≤–µ—Ä–∂–¥–µ–Ω–∏—è —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞ (unix timestamp –≤
            –º–∏–ª–ª–∏—Å–µ–∫—É–Ω–¥–∞—Ö).
          type: integer
          format: int64
          example: 1698361458054
        data:
          description: >
            –î–∞–Ω–Ω—ã–µ –æ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª–µ –∏ —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞ (–º–æ–∂–µ—Ç –±—ã—Ç—å –ø—É—Å—Ç—ã–º
            –æ–±—ä–µ–∫—Ç–æ–º).

            –û–±—ä–µ–∫—Ç `data` —Å–æ—Å—Ç–æ–∏—Ç –∏–∑ –ø–∞—Ä –∫–ª—é—á-–∑–Ω–∞—á–µ–Ω–∏–µ. –ù–∞–∑–≤–∞–Ω–∏–µ –∫–ª—é—á–∞ —è–≤–ª—è–µ—Ç—Å—è
            –ø—Ä–æ–∏–∑–≤–æ–ª—å–Ω—ã–º, –Ω–∞–ø—Ä–∏–º–µ—Ä: `account` –∏–ª–∏ `fio`.

            –ó–Ω–∞—á–µ–Ω–∏–µ–º —è–≤–ª—è–µ—Ç—Å—è –æ–±—ä–µ–∫—Ç —Å –µ–¥–∏–Ω—Å—Ç–≤–µ–Ω–Ω—ã–º —Å–≤–æ–π—Å—Ç–≤–æ–º `value` (—Ç–∏–ø
            `string`).
          type: object
          example:
            account:
              value: '123456789'
            fio:
              value: –ò–≤–∞–Ω–æ–≤ –ò–≤–∞–Ω –ò–≤–∞–Ω–æ–≤–∏—á
        amount:
          description: |
            –°—É–º–º–∞ –ø–ª–∞—Ç–µ–∂–∞ –≤ —Ç–∏–π–∏–Ω–∞—Ö.
          type: integer
          format: int64
          example: 2500000
      required:
        - serviceId
        - transId
        - status
        - confirmTime
        - amount
    ConfirmError:
      type: object
      properties:
        serviceId:
          description: |
            –ò–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä —Å–µ—Ä–≤–∏—Å–∞ –∑–∞ –∫–æ—Ç–æ—Ä—ã–π –ø—Ä–æ–∏–∑–≤–æ–¥–∏—Ç—Å—è –æ–ø–ª–∞—Ç–∞.
          type: integer
          format: int64
          example: 101202
        transId:
          description: |
            –ò–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞, —Å–æ–∑–¥–∞–Ω–Ω–æ–π –≤ Uzum Bank.
          type: string
          format: uuid
          example: 5c398d7e-76b6-11ee-96da-f3a095c6289d
        status:
          description: |
            –°—Ç–∞—Ç—É—Å —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞.
          type: string
          enum:
            - FAILED
          example: FAILED
        confirmTime:
          description: >
            –í—Ä–µ–º—è –ø–æ–¥—Ç–≤–µ—Ä–∂–¥–µ–Ω–∏—è —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞ (unix timestamp –≤
            –º–∏–ª–ª–∏—Å–µ–∫—É–Ω–¥–∞—Ö).
                 
          type: integer
          format: int64
          example: 1698361458054
        errorCode:
          description: >
            –ö–æ–¥ –æ—à–∏–±–∫–∏ –ø–æ–¥—Ç–≤–µ—Ä–∂–¥–µ–Ω–∏—è —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞.



            –ö–æ–¥ –æ—à–∏–±–∫–∏  | –û–ø–∏—Å–∞–Ω–∏–µ –æ—à–∏–±–∫–∏ | –ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–∏  

            -|-|-

            10001 | –î–æ—Å—Ç—É–ø –∑–∞–ø—Ä–µ—â–µ–Ω | –û—à–∏–±–∫–∞ –∞–≤—Ç–æ—Ä–∏–∑–∞—Ü–∏–∏ 

            10002 | –û—à–∏–±–∫–∞ –ø–∞—Ä—Å–∏–Ω–≥–∞ JSON –æ–±—ä–µ–∫—Ç–∞ —Å –ø–∞—Ä–∞–º–µ—Ç—Ä–∞–º–∏ –∑–∞–ø—Ä–æ—Å–∞ 

            10003 | –ù–µ–¥–æ–ø—É—Å—Ç–∏–º–∞—è –æ–ø–µ—Ä–∞—Ü–∏—è | –ù–µ–≤–µ—Ä–Ω—ã–π HTTP –º–µ—Ç–æ–¥ 

            10005 | –û—Ç—Å—É—Ç—Å—Ç–≤—É—é—Ç –æ–±—è–∑–∞—Ç–µ–ª—å–Ω—ã–µ –ø–∞—Ä–∞–º–µ—Ç—Ä—ã –≤ –∑–∞–ø—Ä–æ—Å–µ 

            10014 | –¢—Ä–∞–Ω–∑–∞–∫—Ü–∏—è –Ω–µ –Ω–∞–π–¥–µ–Ω–∞ 

            10015 | –¢—Ä–∞–Ω–∑–∞–∫—Ü–∏—è –æ—Ç–º–µ–Ω–µ–Ω–∞

            10016 | –¢—Ä–∞–Ω–∑–∞–∫—Ü–∏—è —Å –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä–æ–º `transId` —É–∂–µ –ø–æ–¥—Ç–≤–µ—Ä–∂–¥–µ–Ω–∞

            99999 | –û—à–∏–±–∫–∞ –ø—Ä–æ–≤–µ—Ä–∫–∏ –¥–∞–Ω–Ω—ã—Ö | –°–µ—Ä–≤–∏—Å –Ω–µ–¥–æ—Å—Ç—É–ø–µ–Ω, –ø–æ–≤—Ç–æ—Ä–∏—Ç–µ
            –ø–æ–ø—ã—Ç–∫—É –ø–æ–∑–∂–µ 
          type: string
          example: '10014'
      required:
        - errorCode
    ReverseRequest:
      type: object
      properties:
        serviceId:
          description: |
            –ò–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä —Å–µ—Ä–≤–∏—Å–∞ –∑–∞ –∫–æ—Ç–æ—Ä—ã–π –ø—Ä–æ–∏–∑–≤–æ–¥–∏—Ç—Å—è –æ–ø–ª–∞—Ç–∞.
          type: integer
          format: int64
          example: 101202
        timestamp:
          description: |
            –í—Ä–µ–º—è –æ—Ç–ø—Ä–∞–≤–∫–∏ –∑–∞–ø—Ä–æ—Å–∞ (unix timestamp –≤ –º–∏–ª–ª–∏—Å–µ–∫—É–Ω–¥–∞—Ö).
          type: integer
          format: int64
          example: 1698361456728
        transId:
          description: |
            –ò–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞, —Å–æ–∑–¥–∞–Ω–Ω–æ–π –≤ Uzum Bank.
          type: string
          format: uuid
          example: 5c398d7e-76b6-11ee-96da-f3a095c6289d
      required:
        - serviceId
        - timestamp
        - transId
    Reverse:
      type: object
      properties:
        serviceId:
          description: |
            –ò–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä —Å–µ—Ä–≤–∏—Å–∞ –∑–∞ –∫–æ—Ç–æ—Ä—ã–π –ø—Ä–æ–∏–∑–≤–æ–¥–∏—Ç—Å—è –æ–ø–ª–∞—Ç–∞.
          type: integer
          format: int64
          example: 101202
        transId:
          description: |
            –ò–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞, —Å–æ–∑–¥–∞–Ω–Ω–æ–π –≤ Uzum Bank.
          type: string
          format: uuid
          example: 5c398d7e-76b6-11ee-96da-f3a095c6289d
        status:
          description: |
            –°—Ç–∞—Ç—É—Å —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞.
          type: string
          enum:
            - REVERSED
          example: REVERSED
        reverseTime:
          description: |
            –í—Ä–µ–º—è –æ—Ç–º–µ–Ω—ã —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞ (unix timestamp –≤ –º–∏–ª–ª–∏—Å–µ–∫—É–Ω–¥–∞—Ö).
          type: integer
          format: int64
          example: 1698361458054
        data:
          description: >
            –î–∞–Ω–Ω—ã–µ –æ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª–µ –∏ —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞ (–º–æ–∂–µ—Ç –±—ã—Ç—å –ø—É—Å—Ç—ã–º
            –æ–±—ä–µ–∫—Ç–æ–º).

            –û–±—ä–µ–∫—Ç `data` —Å–æ—Å—Ç–æ–∏—Ç –∏–∑ –ø–∞—Ä –∫–ª—é—á-–∑–Ω–∞—á–µ–Ω–∏–µ. –ù–∞–∑–≤–∞–Ω–∏–µ –∫–ª—é—á–∞ —è–≤–ª—è–µ—Ç—Å—è
            –ø—Ä–æ–∏–∑–≤–æ–ª—å–Ω—ã–º, –Ω–∞–ø—Ä–∏–º–µ—Ä: `account` –∏–ª–∏ `fio`.
          type: object
          example:
            account:
              value: '123456789'
            fio:
              value: –ò–≤–∞–Ω–æ–≤ –ò–≤–∞–Ω –ò–≤–∞–Ω–æ–≤–∏—á
        amount:
          description: |
            –°—É–º–º–∞ –ø–ª–∞—Ç–µ–∂–∞ –≤ —Ç–∏–π–∏–Ω–∞—Ö.
          type: integer
          format: int64
          example: 2500000
      required:
        - serviceId
        - transId
        - status
        - confirmTime
        - amount
    ReverseError:
      type: object
      properties:
        serviceId:
          description: |
            –ò–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä —Å–µ—Ä–≤–∏—Å–∞ –∑–∞ –∫–æ—Ç–æ—Ä—ã–π –ø—Ä–æ–∏–∑–≤–æ–¥–∏—Ç—Å—è –æ–ø–ª–∞—Ç–∞.
          type: integer
          format: int64
          example: 101202
        transId:
          description: |
            –ò–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞, —Å–æ–∑–¥–∞–Ω–Ω–æ–π –≤ Uzum Bank.
          type: string
          format: uuid
          example: 5c398d7e-76b6-11ee-96da-f3a095c6289d
        status:
          description: |
            –°—Ç–∞—Ç—É—Å —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞.
          type: string
          enum:
            - FAILED
          example: FAILED
        reverseTime:
          description: |
            –í—Ä–µ–º—è –æ—Ç–º–µ–Ω—ã —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞ (unix timestamp –≤ –º–∏–ª–ª–∏—Å–µ–∫—É–Ω–¥–∞—Ö).
                        
          type: integer
          format: int64
          example: 1698361458054
        errorCode:
          description: >
            –ö–æ–¥ –æ—à–∏–±–∫–∏ –ø–æ–¥—Ç–≤–µ—Ä–∂–¥–µ–Ω–∏—è —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞.


            –ö–æ–¥ –æ—à–∏–±–∫–∏ | –û–ø–∏—Å–∞–Ω–∏–µ –æ—à–∏–±–∫–∏ | –ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–∏ 

            -|-|-

            10001 | –î–æ—Å—Ç—É–ø –∑–∞–ø—Ä–µ—â–µ–Ω | –û—à–∏–±–∫–∞ –∞–≤—Ç–æ—Ä–∏–∑–∞—Ü–∏–∏

            10002 | –û—à–∏–±–∫–∞ –ø–∞—Ä—Å–∏–Ω–≥–∞ JSON –æ–±—ä–µ–∫—Ç–∞ —Å –ø–∞—Ä–∞–º–µ—Ç—Ä–∞–º–∏ –∑–∞–ø—Ä–æ—Å–∞ 

            10003 | –ù–µ–¥–æ–ø—É—Å—Ç–∏–º–∞—è –æ–ø–µ—Ä–∞—Ü–∏—è | –ù–µ–≤–µ—Ä–Ω—ã–π HTTP –º–µ—Ç–æ–¥ 

            10005 | –û—Ç—Å—É—Ç—Å—Ç–≤—É—é—Ç –æ–±—è–∑–∞—Ç–µ–ª—å–Ω—ã–µ –ø–∞—Ä–∞–º–µ—Ç—Ä—ã –≤ –∑–∞–ø—Ä–æ—Å–µ

            10014 | –¢—Ä–∞–Ω–∑–∞–∫—Ü–∏—è –Ω–µ –Ω–∞–π–¥–µ–Ω–∞

            10017 | –ù–µ–≤–æ–∑–º–æ–∂–Ω–æ –æ—Ç–º–µ–Ω–∏—Ç—å —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏—é

            10018 | –¢—Ä–∞–Ω–∑–∞–∫—Ü–∏—è —Å –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä–æ–º `transId` —É–∂–µ –æ—Ç–º–µ–Ω–µ–Ω–∞ 

            99999 | –û—à–∏–±–∫–∞ –ø—Ä–æ–≤–µ—Ä–∫–∏ –¥–∞–Ω–Ω—ã—Ö | –°–µ—Ä–≤–∏—Å –Ω–µ–¥–æ—Å—Ç—É–ø–µ–Ω, –ø–æ–≤—Ç–æ—Ä–∏—Ç–µ
            –ø–æ–ø—ã—Ç–∫—É –ø–æ–∑–∂–µ 
          type: string
          example: '10017'
      required:
        - errorCode
    StatusRequest:
      type: object
      properties:
        serviceId:
          description: |
            –ò–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä —Å–µ—Ä–≤–∏—Å–∞ –∑–∞ –∫–æ—Ç–æ—Ä—ã–π –ø—Ä–æ–∏–∑–≤–æ–¥–∏—Ç—Å—è –æ–ø–ª–∞—Ç–∞.
          type: integer
          format: int64
          example: 101202
        timestamp:
          description: |
            –í—Ä–µ–º—è –æ—Ç–ø—Ä–∞–≤–∫–∏ –∑–∞–ø—Ä–æ—Å–∞ (unix timestamp –≤ –º–∏–ª–ª–∏—Å–µ–∫—É–Ω–¥–∞—Ö).
          type: integer
          format: int64
          example: 1698361456728
        transId:
          description: |
            –ò–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞, —Å–æ–∑–¥–∞–Ω–Ω–æ–π –≤ Uzum Bank.
          type: string
          format: uuid
          example: 5c398d7e-76b6-11ee-96da-f3a095c6289d
      required:
        - serviceId
        - timestamp
        - transId
    Status:
      type: object
      properties:
        serviceId:
          description: |
            –ò–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä —Å–µ—Ä–≤–∏—Å–∞ –∑–∞ –∫–æ—Ç–æ—Ä—ã–π –ø—Ä–æ–∏–∑–≤–æ–¥–∏—Ç—Å—è –æ–ø–ª–∞—Ç–∞.
          type: integer
          format: int64
          example: 101202
        transId:
          description: |
            –ò–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞, —Å–æ–∑–¥–∞–Ω–Ω–æ–π –≤ Uzum Bank.
          type: string
          format: uuid
          example: 5c398d7e-76b6-11ee-96da-f3a095c6289d
        status:
          description: |
            –°—Ç–∞—Ç—É—Å —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞.
          type: string
          enum:
            - CREATED
            - CONFIRMED
            - REVERSED
          example: CONFIRMED
        transTime:
          description: |
            –í—Ä–µ–º—è —Å–æ–∑–¥–∞–Ω–∏—è —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞ (unix timestamp –≤ –º–∏–ª–ª–∏—Å–µ–∫—É–Ω–¥–∞—Ö).
          type: integer
          format: int64
          example: 1698361458054
        confirmTime:
          description: >
            –í—Ä–µ–º—è –ø–æ–¥—Ç–≤–µ—Ä–∂–¥–µ–Ω–∏—è —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞ (unix timestamp –≤
            –º–∏–ª–ª–∏—Å–µ–∫—É–Ω–¥–∞—Ö).
          oneOf:
            - type: integer
              format: int64
            - type: 'null'
          example: 1698361458054
        reverseTime:
          description: |
            –í—Ä–µ–º—è –æ—Ç–º–µ–Ω—ã —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞ (unix timestamp –≤ –º–∏–ª–ª–∏—Å–µ–∫—É–Ω–¥–∞—Ö).
          oneOf:
            - type: integer
              format: int64
            - type: 'null'
          example: null
        data:
          description: >
            –î–∞–Ω–Ω—ã–µ –æ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª–µ –∏ —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞ (–º–æ–∂–µ—Ç –±—ã—Ç—å –ø—É—Å—Ç—ã–º
            –æ–±—ä–µ–∫—Ç–æ–º).

            –û–±—ä–µ–∫—Ç `data` —Å–æ—Å—Ç–æ–∏—Ç –∏–∑ –ø–∞—Ä –∫–ª—é—á-–∑–Ω–∞—á–µ–Ω–∏–µ. –ù–∞–∑–≤–∞–Ω–∏–µ –∫–ª—é—á–∞ —è–≤–ª—è–µ—Ç—Å—è
            –ø—Ä–æ–∏–∑–≤–æ–ª—å–Ω—ã–º, –Ω–∞–ø—Ä–∏–º–µ—Ä: `account` –∏–ª–∏ `fio`.

            –ó–Ω–∞—á–µ–Ω–∏–µ–º —è–≤–ª—è–µ—Ç—Å—è –æ–±—ä–µ–∫—Ç —Å –µ–¥–∏–Ω—Å—Ç–≤–µ–Ω–Ω—ã–º —Å–≤–æ–π—Å—Ç–≤–æ–º `value` (—Ç–∏–ø
            `string`).
          type: object
          example:
            account:
              value: '123456789'
            fio:
              value: –ò–≤–∞–Ω–æ–≤ –ò–≤–∞–Ω –ò–≤–∞–Ω–æ–≤–∏—á
        amount:
          description: |
            –°—É–º–º–∞ –ø–ª–∞—Ç–µ–∂–∞ –≤ —Ç–∏–π–∏–Ω–∞—Ö.
          type: integer
          format: int64
          example: 2500000
      required:
        - serviceId
        - transId
        - status
        - transTime
    StatusError:
      type: object
      properties:
        serviceId:
          description: |
            –ò–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä —Å–µ—Ä–≤–∏—Å–∞ –∑–∞ –∫–æ—Ç–æ—Ä—ã–π –ø—Ä–æ–∏–∑–≤–æ–¥–∏—Ç—Å—è –æ–ø–ª–∞—Ç–∞.
          type: integer
          format: int64
          example: 101202
        transId:
          description: |
            –ò–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞, —Å–æ–∑–¥–∞–Ω–Ω–æ–π –≤ Uzum Bank.
          type: string
          format: uuid
          example: 5c398d7e-76b6-11ee-96da-f3a095c6289d
        status:
          description: |
            –°—Ç–∞—Ç—É—Å —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞.
          type: string
          enum:
            - FAILED
          example: FAILED
        transTime:
          description: |
            –í—Ä–µ–º—è —Å–æ–∑–¥–∞–Ω–∏—è —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞ (unix timestamp –≤ –º–∏–ª–ª–∏—Å–µ–∫—É–Ω–¥–∞—Ö).
          type: integer
          format: int64
          example: 1698361458054
        confirmTime:
          description: >
            –í—Ä–µ–º—è –ø–æ–¥—Ç–≤–µ—Ä–∂–¥–µ–Ω–∏—è —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞ (unix timestamp –≤
            –º–∏–ª–ª–∏—Å–µ–∫—É–Ω–¥–∞—Ö).
          oneOf:
            - type: integer
              format: int64
            - type: 'null'
          example: 1698361458054
        reverseTime:
          description: |
            –í—Ä–µ–º—è –æ—Ç–º–µ–Ω—ã —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞ (unix timestamp –≤ –º–∏–ª–ª–∏—Å–µ–∫—É–Ω–¥–∞—Ö).
          oneOf:
            - type: integer
              format: int64
            - type: 'null'
          example: null
        errorCode:
          description: >
            –ö–æ–¥ –æ—à–∏–±–∫–∏ –ø–æ–ª—É—á–µ–Ω–∏—è —Å—Ç–∞—Ç—É—Å–∞ —Ç—Ä–∞–Ω–∑–∞–∫—Ü–∏–∏ –ø–ª–∞—Ç–µ–∂–∞.



            –ö–æ–¥ –æ—à–∏–±–∫–∏  | –û–ø–∏—Å–∞–Ω–∏–µ –æ—à–∏–±–∫–∏  | –ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–∏ / 

            -|-|-

            10001 | –î–æ—Å—Ç—É–ø –∑–∞–ø—Ä–µ—â–µ–Ω  | –û—à–∏–±–∫–∞ –∞–≤—Ç–æ—Ä–∏–∑–∞—Ü–∏–∏

            10002 | –û—à–∏–±–∫–∞ –ø–∞—Ä—Å–∏–Ω–≥–∞ JSON –æ–±—ä–µ–∫—Ç–∞ —Å –ø–∞—Ä–∞–º–µ—Ç—Ä–∞–º–∏ –∑–∞–ø—Ä–æ—Å–∞

            10003 | –ù–µ–¥–æ–ø—É—Å—Ç–∏–º–∞—è –æ–ø–µ—Ä–∞—Ü–∏—è | –ù–µ–≤–µ—Ä–Ω—ã–π HTTP –º–µ—Ç–æ–¥ 

            10005 | –û—Ç—Å—É—Ç—Å—Ç–≤—É—é—Ç –æ–±—è–∑–∞—Ç–µ–ª—å–Ω—ã–µ –ø–∞—Ä–∞–º–µ—Ç—Ä—ã –≤ –∑–∞–ø—Ä–æ—Å–µ 

            10014 | –¢—Ä–∞–Ω–∑–∞–∫—Ü–∏—è –Ω–µ –Ω–∞–π–¥–µ–Ω–∞ 

            99999 | –û—à–∏–±–∫–∞ –ø—Ä–æ–≤–µ—Ä–∫–∏ –¥–∞–Ω–Ω—ã—Ö| –°–µ—Ä–≤–∏—Å –Ω–µ–¥–æ—Å—Ç—É–ø–µ–Ω, –ø–æ–≤—Ç–æ—Ä–∏—Ç–µ –ø–æ–ø—ã—Ç–∫—É
            –ø–æ–∑–∂–µ 
          type: string
          example: '10014'
      required:
        - errorCode
